version: '3'
services:
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    environment:
      - grpc.port=50050
    ports:
      - "50050:50050"  # gRPC port
      - "8080:8080"    # HTTP port
    depends_on:
      - secondary1
      - secondary2
    networks:
      replog-network:
        aliases:
          - master

  secondary1:
    build:
      context: ./secondary
      dockerfile: Dockerfile
    environment:
      - grpc.port=50051
      - grpc.host=secondary1
      - master.host=master
      - master.port=8080
    ports:
      - "50051:50051"
      - "8081:8080"
    networks:
      replog-network:
        aliases:
          - secondary1

  secondary2:
    build:
      context: ./secondary
      dockerfile: Dockerfile
    environment:
      - grpc.port=50052
      - grpc.host=secondary2
      - master.host=master
      - master.port=8080
    ports:
      - "50052:50052"
      - "8082:8080"
    networks:
      replog-network:
        aliases:
          - secondary2

networks:
  replog-network:
    driver: bridge