version: '3'
services:
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - secondary1
      - secondary2
    networks:
      replog-network:
        aliases:
          - master
  secondary1:
    build:
      context: ./secondary
      dockerfile: Dockerfile
    command: ["50051"]
    ports:
      - "50051:50051"
    networks:
      replog-network:
        aliases:
          - secondary1
  secondary2:
    build:
      context: ./secondary
      dockerfile: Dockerfile
    command: ["50052"]
    ports:
      - "50052:50052"
    networks:
      replog-network:
        aliases:
          - secondary2
networks:
  replog-network:
    driver: bridge